# Script zum Hinzufügen von first/text Feldern zu allen Akronimmen im Glossar

$glossaryPath = "E:\WebstormProjects\untitled\thesis\glossary.tex"
$content = Get-Content $glossaryPath -Raw -Encoding UTF8

# Liste aller Akronyme mit ihren Langformen (aus description extrahiert)
$acronymReplacements = @{
    "PABX" = "Private Automatic Branch Exchange"
    "DPIA" = "Data Protection Impact Assessment"
    "GDPR" = "General Data Protection Regulation"
    "MANO" = "Management and Orchestration"
    "BPO" = "Business Process Outsourcing"
    "EIA" = "Ethical Impact Assessment"
    "ALSA" = "Advanced Linux Sound Architecture"
    "HTTP" = "Hypertext Transfer Protocol"
    "ARI" = "Asterisk REST Interface"
    "VM" = "Virtuelle Maschine"
    "RFC" = "Request for Comments"
    "IETF" = "Internet Engineering Task Force"
    "DID" = "Direct Inward Dialing"
    "NDJSON" = "Newline Delimited JSON"
    "PESQ" = "Perceptual Evaluation of Speech Quality"
    "POLQA" = "Perceptual Objective Listening Quality Assessment"
    "PCM" = "Pulse Code Modulation"
    "TCP" = "Transmission Control Protocol"
    "RTC" = "Real-Time Communication"
    "PJSIP" = "Open-Source-Bibliothek für SIP-basierte Sprach- und Videoübertragung"
    "UDP" = "User Datagram Protocol"
    "JWT" = "JSON Web Token"
    "RMS" = "Root Mean Square"
    "DTMF" = "Dual-Tone Multi-Frequency"
    "DACH" = "Deutschland, Österreich und die Schweiz"
    "HTTPS" = "Hypertext Transfer Protocol Secure"
    "NLP" = "Natural Language Processing"
    "ISO" = "International Organization for Standardization"
    "VLAN" = "Virtual Local Area Network"
    "KMS" = "Key Management Service"
    "DSGVO" = "Datenschutz-Grundverordnung"
    "PCM16" = "Pulse Code Modulation mit 16 Bit Auflösung"
    "STUN" = "Session Traversal Utilities for NAT"
    "TURN" = "Traversal Using Relays around NAT"
    "RTP-Bridge" = "Komponente für RTP-Mediendatenströme"
    "KMU" = "kleine und mittelständische Unternehmen"
    "SIP" = "Session Initiation Protocol"
    "LLM" = "Large Language Model"
    "WebRTC" = "Web Real-Time Communication"
    "VoIP" = "Voice over Internet Protocol"
    "KI" = "Künstliche Intelligenz"
    "AI" = "Artificial Intelligence"
    "API" = "Application Programming Interface"
    "RTP" = "Real-time Transport Protocol"
    "RTCP" = "RTP Control Protocol"
    "SRTP" = "Secure Real-time Transport Protocol"
    "DTLS" = "Datagram Transport Layer Security"
    "NAT" = "Network Address Translation"
    "ICE" = "Interactive Connectivity Establishment"
    "ASR" = "Automatic Speech Recognition"
    "STT" = "Speech-to-Text"
    "TTS" = "Text-to-Speech"
    "VAD" = "Voice Activity Detection"
    "MOS" = "Mean Opinion Score"
    "ITU-T" = "International Telecommunication Union"
    "PBX" = "Private Branch Exchange"
    "IVR" = "Interactive Voice Response"
    "NFV" = "Network Function Virtualization"
    "ETSI" = "European Telecommunications Standards Institute"
    "VNF" = "Virtualized Network Function"
    "NFVI" = "Network Function Virtualization Infrastructure"
    "NFVO" = "Network Function Virtualization Orchestration"
    "CDR" = "Call Detail Record"
    "SLA" = "Service Level Agreement"
    "RBAC" = "Role-Based Access Control"
    "TLS" = "Transport Layer Security"
    "mTLS" = "Mutual TLS"
    "DPA" = "Data Processing Agreement"
    "SCC" = "Standard Contractual Clauses"
    "QoS" = "Quality of Service"
    "PII" = "Personally Identifiable Information"
    "CPaaS" = "Communications Platform as a Service"
    "SFU" = "Selective Forwarding Unit"
    "CPU" = "Central Processing Unit"
    "RAM" = "Random Access Memory"
    "JSON" = "JavaScript Object Notation"
    "SDK" = "Software Development Kit"
    "CLI" = "Command-Line Interface"
    "REST" = "Representational State Transfer"
    "UI" = "User Interface"
    "PSTN" = "Public Switched Telephone Network"
    "OSS" = "Open Source Software"
    "SPA" = "Single-Page Application"
    "E2E" = "End-to-End"
    "RAG" = "Retrieval-Augmented Generation"
    "MEC" = "Multi-access Edge Computing"
    "TTL" = "Time-To-Live"
    "YAML" = "YAML Ain't Markup Language"
    "LAN" = "Local Area Network"
    "AVV" = "Auftragsverarbeitungsvertrag"
}

$count = 0
foreach ($acronym in $acronymReplacements.Keys) {
    $longForm = $acronymReplacements[$acronym]
    $pattern = "\\newglossaryentry\{gls-$([Regex]::Escape($acronym))\}\{\s*type=fachwort,\s*name=$([Regex]::Escape($acronym)),"

    if ($content -match $pattern) {
        $replacement = "\newglossaryentry{gls-$acronym}{ `n  type=fachwort, `n  name=$acronym, `n  first={$longForm ($acronym)}, `n  text=$acronym,"
        $content = $content -replace $pattern, $replacement
        $count++
        Write-Host "✓ $acronym updated"
    }
}

Set-Content -Path $glossaryPath -Value $content -Encoding UTF8
Write-Host ""
Write-Host "✓ $count Akronyme aktualisiert mit first/text Feldern!"

